laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('portfolio/{portfolio_slug?}', 'PortfolioController@index')->name('portfolio');
    Route::get('apresentacoes/{projeto_slug?}', 'ProjetosController@index')->name('projetos');
    Route::get('clipping', 'ClippingController@index')->name('clipping');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::get('clipping/delete-image/{midia_id}', 'ClippingController@deleteImage')->name('painel.clipping.deleteImage');
        Route::get('midia/delete-pdf/{midia_id}', 'ClippingController@deletePdf')->name('painel.clipping.deletePdf');
        Route::resource('clipping', 'ClippingController');
        Route::get('clipping/{clipping}/imagens/clear', [
            'as'   => 'painel.clipping.imagens.clear',
            'uses' => 'ClippingImagensController@clear'
        ]);
        Route::resource('clipping.imagens', 'ClippingImagensController');

        Route::resource('projetos-capa', 'ProjetosCapaController', ['only' => ['index', 'update']]);
        Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::resource('projetos.imagens', 'ProjetosImagensController');

		Route::resource('portfolio-capa', 'PortfolioCapaController', ['only' => ['index', 'update']]);
		Route::resource('portfolio', 'PortfolioController');
        Route::get('portfolio/{portfolio}/imagens/clear', [
            'as'   => 'painel.portfolio.imagens.clear',
            'uses' => 'PortfolioImagensController@clear'
        ]);
        Route::resource('portfolio.imagens', 'PortfolioImagensController');

		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ClippingController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Helpers\Tools;

class ClippingController extends Controller
{
    public function index()
    {
        $registros = Clipping::ordenados()->get();

        return view('painel.clipping.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.clipping.create');
    }

    public function store(ClippingRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Clipping::upload_imagem();
            if (isset($input['video_codigo']) && isset($input['video_tipo'])) $input['video_capa'] = Tools::videoThumb($request->get('video_tipo'), $request->get('video_codigo'));
            if ($request->hasFile('pdf')) $input['pdf'] = Clipping::uploadPdf();

            Clipping::create($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Clipping $registro)
    {
        return view('painel.clipping.edit', compact('registro'));
    }

    public function update(ClippingRequest $request, Clipping $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Clipping::upload_imagem();
            if ($input['video_codigo'] !== $registro->video_codigo || $input['video_tipo'] !== $registro->video_tipo) {
                $input['video_capa'] = Tools::videoThumb($input['video_tipo'], $input['video_codigo']);
            }
            if ($request->hasFile('pdf')) $input['pdf'] = Clipping::uploadPdf();

            $registro->update($input);
            return redirect()->route('painel.clipping.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Clipping $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.clipping.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function deleteImage($id)
    {
        try {

            $midia = Clipping::find($id);
            $midia->imagem = null;
            $midia->save();

            return back()->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }

    public function deletePdf($id)
    {
        try {

            $midia = Clipping::find($id);
            $midia->pdf = null;
            $midia->save();

            return back()->with('success', 'Arquivo PDF excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir PDF: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClippingImagensRequest;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Models\ClippingImagem;
use App\Helpers\CropImage;

class ClippingImagensController extends Controller
{
    private $image_config = [
        [
            'width'   => 360,
            'height'  => 180,
            'path'    => 'assets/img/clipping/imagens/thumbs/'
        ],
        [
            'width'   => 940,
            'height'  => null,
            'upsize'  => true,
            'path'    => 'assets/img/clipping/imagens/'
        ]
    ];

    public function index(Clipping $clipping)
    {
        $imagens = ClippingImagem::clipping($clipping->id)->ordenados()->get();

        return view('painel.clipping.imagens.index', compact('imagens', 'clipping'));
    }

    public function show(Clipping $clipping, ClippingImagem $imagem)
    {
        return $imagem;
    }

    public function create(Clipping $clipping)
    {
        return view('painel.clipping.imagens.create', compact('clipping'));
    }

    public function store(Clipping $clipping, ClippingImagensRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = $clipping->imagens()->create($input);

            $view = view('painel.clipping.imagens.imagem', compact('clipping', 'imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Clipping $clipping, ClippingImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }

    public function clear(Clipping $clipping)
    {
        try {

            $clipping->imagens()->delete();
            return redirect()->route('painel.clipping.imagens.index', $clipping)
                             ->with('success', 'Imagens excluídas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/PerfilController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PerfilRequest;
use App\Http\Controllers\Controller;

use App\Models\Perfil;

class PerfilController extends Controller
{
    public function index()
    {
        $registro = Perfil::first();

        return view('painel.perfil.edit', compact('registro'));
    }

    public function update(PerfilRequest $request, Perfil $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Perfil::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.perfil.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PortfolioCapaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PortfolioCapaRequest;
use App\Http\Controllers\Controller;

use App\Models\PortfolioCapa;

class PortfolioCapaController extends Controller
{
    public function index()
    {
        $registro = PortfolioCapa::first();

        return view('painel.portfolio-capa.edit', compact('registro'));
    }

    public function update(PortfolioCapaRequest $request, PortfolioCapa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = PortfolioCapa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.portfolio-capa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PortfolioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PortfolioRequest;
use App\Http\Controllers\Controller;

use App\Models\Portfolio;

class PortfolioController extends Controller
{
    public function index()
    {
        $registros = Portfolio::ordenados()->get();

        return view('painel.portfolio.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.portfolio.create');
    }

    public function store(PortfolioRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Portfolio::upload_capa();

            Portfolio::create($input);
            return redirect()->route('painel.portfolio.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Portfolio $registro)
    {
        return view('painel.portfolio.edit', compact('registro'));
    }

    public function update(PortfolioRequest $request, Portfolio $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Portfolio::upload_capa();

            $registro->update($input);
            return redirect()->route('painel.portfolio.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Portfolio $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.portfolio.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/portfolio/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Portfolio /</small> Adicionar Portfolio</h2>
    </legend>

    {!! Form::open(['route' => 'painel.portfolio.store', 'files' => true]) !!}

        @include('painel.portfolio.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/portfolio/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Portfolio /</small> Editar Portfolio</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.portfolio.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.portfolio.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/portfolio/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('local', 'Local') !!}
    {!! Form::text('local', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('ano', 'Ano') !!}
    {!! Form::text('ano', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('parceria', 'Parceria') !!}
    {!! Form::text('parceria', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('capa', 'Capa') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/portfolio/capa/'.$registro->capa) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('capa', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.portfolio.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/portfolio/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Portfolio
            <div class="btn-group pull-right">
                <a href="{{ route('painel.portfolio.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Portfolio</a>
            </div>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="portfolio">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th>Capa</th>
                <th>Imagens</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td><img src="{{ asset('assets/img/portfolio/capa/'.$registro->capa) }}" style="width: 100%; max-width:100px;" alt=""></td>
                <td><a href="{{ route('painel.portfolio.imagens.index', $registro->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.portfolio.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.portfolio.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection